credentials:
  username: "josdem"
  password: "12345678"
spring:
  datasource:
    url: "jdbc:mysql://localhost/spring_boot_security"
    username: "securityUser"
    password: "secur1tyDB.D0"
    driver-class-name: "com.mysql.jdbc.Driver"
  jpa:
    generate-ddl: true
